image: ubuntu

# stack: go 1.12

version: '{build}'

cache:
- go1.12.1.deb

install:
- 'if [[ $APPVEYOR_REPO_TAG == "true" ]]; then appveyor UpdateBuild -Version "$(git describe --tags --always).$APPVEYOR_BUILD_ID"; else appveyor UpdateBuild -Version "$(git rev-parse --short HEAD).$APPVEYOR_BUILD_ID"; fi'
- 'wget --no-clobber -O go1.12.1.deb https://deb.geek1011.net/pool/main/g/go/go_1.12.1-godeb1_amd64.deb || true'
- sudo dpkg -i go1.12.1.deb
- go mod download

test_script:
- go test -v ./...
- 'go run jiup/rules/reachability-test/main.go || [[ $APPVEYOR_FORCED_BUILD == "true" ]]'

test: off

# TODO: deployments
